import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# --- Configuration ---
# Read the file generated by the previous step
INPUT_FILE = "../Top_Individual_Poses_Ranked.csv" 
OUTPUT_PLOT = "Prioritization_Scatter_Plot_Final.png"
RAW_DATA_FILE = "../MMPBSA_Analysis_Ready.csv" # Use this for full data background

# Baseline NAD binding energy (from your console output)
DELTA_G_NAD_APO = -80.77

# Define the single best pose identified for specific highlighting
BEST_POSE_MOL = 'ZINC12660894'
BEST_POSE_TAG = 'dock6'
REF_4TQ = '4zzj_nad_p53_4tq'

def plot_prioritization_map(ranking_file, raw_data_file, output_plot):
    """
    Generates a scatter plot using the raw data for context and highlighting 
    the top pose and reference.
    """
    try:
        # Load the full data from the raw CSV
        df_raw = pd.read_csv(raw_data_file)
        
        # Calculate efficacy (ΔΔG_NAD) on the full dataset for the background scatter
        df_raw['ΔG_Allost'] = df_raw['ΔTOTAL']
        df_raw['ΔΔG_NAD_Efficacy'] = df_raw['NAD_ΔTOTAL'] - DELTA_G_NAD_APO
        
        # Filter out the NAD-only reference (no allosteric ligand)
        plot_df = df_raw[df_raw['Molecule_Name'] != '4zzj_nad_p53'].copy()
        
    except FileNotFoundError:
        print(f"Error: Raw data file '{raw_data_file}' not found. Cannot plot background.")
        return

    # --- 1. Identify Highlight Poses for the foreground ---
    
    # Identify the 4tq reference pose
    ref_pose = plot_df[plot_df['Molecule_Name'] == REF_4TQ]
    
    # Identify the single absolute best pose
    best_pose = plot_df[(plot_df['Molecule_Name'] == BEST_POSE_MOL) & 
                        (plot_df['Pose_Tag'] == BEST_POSE_TAG)]

    # --- 2. Plotting ---
    
    fig, ax = plt.subplots(figsize=(10, 8))

    # Plot all other poses (light gray in background)
    ax.scatter(plot_df['ΔG_Allost'], 
               plot_df['ΔΔG_NAD_Efficacy'], 
               color='lightgray', s=30, alpha=0.6, label='All Other Poses')

    # Plot the 4tq Reference
    if not ref_pose.empty:
        ax.scatter(ref_pose['ΔG_Allost'], 
                   ref_pose['ΔΔG_NAD_Efficacy'], 
                   color='orange', s=100, label='Known Activator (4tq)', marker='D', edgecolor='black')

    # Plot the Single Best Candidate (Highlight with dark color and large size)
    if not best_pose.empty:
        x_val = best_pose['ΔG_Allost'].iloc[0]
        y_val = best_pose['ΔΔG_NAD_Efficacy'].iloc[0]
        
        ax.scatter(x_val, y_val, 
                   color='darkred', s=150, label=f'Top Candidate ({BEST_POSE_MOL}/{BEST_POSE_TAG})', marker='*', edgecolor='black', zorder=5)

        # Annotate the best candidate
        ax.annotate(f"{BEST_POSE_MOL}/{BEST_POSE_TAG}", 
                    (x_val, y_val), 
                    xytext=(-15, 15), 
                    textcoords='offset points',
                    fontsize=9,
                    arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=-0.2", color='darkred'))

    # Set labels and title
    ax.set_xlabel('Ligand Affinity ($\\Delta G_{\\text{Allost}}$, kcal/mol)', fontsize=14)
    ax.set_ylabel('Activation Efficacy ($\\Delta\\Delta G_{\\text{NAD}}$, kcal/mol)', fontsize=14)
    ax.set_title('Allosteric Activator Prioritization Map', fontsize=16)

    # Add Ideal Region Quadrant boundary lines
    ax.axhline(0, color='red', linestyle='--', alpha=0.5, label='Inactivation Threshold')
    ax.legend(loc='lower right')
    ax.grid(True, linestyle=':', alpha=0.5)
    plt.tight_layout()
    
    plt.savefig(output_plot, dpi=300)
    plt.close(fig)
    print(f"\n✅ Prioritization scatter plot generated successfully: **{output_plot}**")

if __name__ == "__main__":
    # We use the raw data file (MMPBSA_Analysis_Ready.csv) to get ALL data points
    # for the background scatter, and we rely on the specific BEST_POSE_* variables
    # set in the configuration based on your console output.
    plot_prioritization_map(INPUT_FILE, RAW_DATA_FILE, OUTPUT_PLOT)
